from django.core.management.base import BaseCommand, CommandError
from vmc_backend.factories import SubmissionFactory

class Command(BaseComand):
    help = "Populates database with entries generated by factories"

    def handle(self, *args, **options):
        pass

